/*******************************************************************************
* File Name: main.c
*
* Version: 2.0
*
* Description:
*  This is source code for example project of the PRS component.
*
*  Parameters used:
*   Run Mode            - Clocked and Api Single Step
*   Resolution          - 16 bits
*   Implementation      - Single Cycle 
*   Polynomial Value    - 0xB400
*   Seed Value          - 0xFFFF
*
*  This project consists of two 16 bits PRS (in the Clocked and API Single Step
*  Run Modes). Clock signal generated by the control register "Clock_Gen".
*  Reset signal generated by the control register "Reset_Gen". Both PRS
*  consistently execute some calculation (SEED_VALUE_COUNT define) at the same
*  time. Its value displayed on LCD and named: SS (Single Step), CL (Clocked).
*  Sofware calculated value output on LCD for verification (SV). After
*  calculation is finished reset of the both PRS are execute. Values after reset
*  are displayed on LCD and named: SS (Single Step), CL (Clocked). All signals
*  changes can be seen on oscillator or signal analyzer at PORT3 [3:0] by
*  default.
* 
*  Defines:
*   SEED_VALUE_COUNT - set number of PRS calculate iteration. (20 by default)
*   DISP_DELAY - set delay of information on the LCD. (1000 by default)
* 
*  LCD view:
*   SV   = Software calculated PRS value.
*   Calc = Hardware calculated PRS iteration at this time.
*   SS   = Hardware calculated Single Step PRS value for current iteration.
*   CL   = Hardware calculated Clocked PRS value for current iteration.
*
********************************************************************************
* Copyright 2012, Cypress Semiconductor Corporation. All rights reserved.
* This software is owned by Cypress Semiconductor Corporation and is protected
* by and subject to worldwide patent and copyright laws and treaties.
* Therefore, you may use this software only as provided in the license agreement
* accompanying the software package from which you obtained this software.
* CYPRESS AND ITS SUPPLIERS MAKE NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
* WITH REGARD TO THIS SOFTWARE, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
*******************************************************************************/

#include <device.h>

#define DISP_DELAY          (1000u)     /* Display delay */
#define SEED_VALUE_COUNT    (20u)       /* Iteration amount */


/*******************************************************************************
* Function Name: Clock1
********************************************************************************
*
* Summary:
*  Generate clock signal.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void Clock1(void)
{
    Clock_Gen_Write(1u);
    CyDelay(1u);
    Clock_Gen_Write(0u);
    CyDelay(1u);
}


/*******************************************************************************
* Function Name: main
********************************************************************************
*
* Summary:
*  Main function performs following functions:
*   1. Generate Clock signals
*   2. Generate Reset signals
*   3. Execute software PRS calculation
*   4. Prints PRS calulated values on LCD.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void main()
{
    uint16 PRS_val = 0u;
    uint16 seed, poly, seed_msb, int_xor_1, int_xor_res, and_op, xor_op;
    uint8 i;

        /* Initialization delay */
        CyDelay(50);

        /* Enable global interrupts. */
        CyGlobalIntEnable;    
        
        /* Initialization */    
    Reset_Gen_Write(0u);
    Clock_Gen_Write(0u);
        LCD_Start();
    PRS_Clocked_Start();
    PRS_SingleStep_Start();

    LCD_Position(0u, 0u);
    LCD_PrintString("PRS16");
    LCD_Position(1u, 0u);
    LCD_PrintString("Example Project");
    CyDelay(DISP_DELAY * 3u);
    LCD_ClearDisplay();
    
    /* Software PRS value calculation */
    PRS_val = PRS_Clocked_Read();
    poly = PRS_Clocked_ReadPolynomial();
    seed = PRS_val; 
    seed_msb=PRS_val;

    for (i=0; i<SEED_VALUE_COUNT; i++)
    {
        seed_msb = seed_msb >> (PRS_Clocked_PRS_SIZE - 1u);
        seed_msb = seed_msb & 1u;
        int_xor_1 = seed_msb ^ 0u;

        if(int_xor_1 == 1)
        {
            int_xor_res=0xffffu; 
        }
        else
        {
            int_xor_res = 0u; 
        }
        
        and_op = int_xor_res & poly;
        xor_op = seed ^ and_op;
        seed = xor_op << 1u;
        seed = seed | int_xor_1;
        seed_msb = seed;
        seed &= PRS_Clocked_MASK;
    }
    
    /* Display Software calculated PRS value on LCD */
    LCD_Position(0u,0u);
    LCD_PrintString("SV=");
    LCD_PrintInt16(seed);    
    CyDelay(DISP_DELAY);

    /* Display Hardware calculated PRS values and current interration on LCD */
    for (i=0; i<=SEED_VALUE_COUNT; i++) 
    {
        LCD_Position(0u,9u);
        LCD_PrintString("Calc=");
        LCD_PrintNumber(i);
        LCD_Position(1, 0u);
        LCD_PrintString("SS=");
        LCD_PrintInt16(PRS_SingleStep_Read());    
        LCD_Position(1u, 9u);
        LCD_PrintString("CL=");
        LCD_PrintInt16(PRS_Clocked_Read());
        CyDelay(DISP_DELAY);
        
        /* Execute calculations */
        PRS_SingleStep_Step();
        Clock1();
    }
    
    /* Clear display after delay */
    CyDelay(DISP_DELAY * 3u);
    LCD_ClearDisplay();
    
    LCD_Position(0u, 0u);
    LCD_PrintString("Reset PRS....");
    CyDelay(DISP_DELAY*3u);
    LCD_ClearDisplay();
    
    /* PRSs initialization and reset */
    PRS_SingleStep_Init();
    Reset_Gen_Write(1u);
    CyDelay(1u);
    Clock1();

    LCD_Position(0u,0u);
    LCD_PrintString("PRS after Reset:");

    /* Display PRS values after reset and initialization */
    LCD_Position(1u, 0u);
    LCD_PrintString("SS=");
    LCD_PrintInt16(PRS_SingleStep_Read());    
    LCD_Position(1u, 9u);
    LCD_PrintString("CL=");
    LCD_PrintInt16(PRS_Clocked_Read());

    /* Empty cycle*/
    for (;;) 
    {
    }
}


/* [] END OF FILE */
